Feed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('FeedApp.urls')),
    path('users/', include('users.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FeedApp/urls.py
from django.urls import path
from . import views

app_name = 'FeedApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('myfeed', views.myfeed, name='myfeed'),
    path('new_post/', views.new_post, name='new_post'),
    path('comments/<int:post_id>/', views.comments, name='comments'),
    path('friendsfeed/', views.friendsfeed, name='friendsfeed'),
    path('friends/', views.friends, name='friends'),
]

users/urls.py
from django.urls import path, include
from . import views  # build-in internal views file of the Users system

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name="register"),
]

FeedApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import Model
from django.db.models.deletion import CASCADE

# Create your models here.

class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    email = models.EmailField(max_length=300,blank=True)
    dob = models.DateField(null=True,blank=True)
    bio = models.TextField(blank=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE) # User entity
    friends = models.ManyToManyField(User,blank=True,related_name='friends')
    created = models.DateTimeField(auto_now=True)
    update = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.user.username}"

STATUS_CHOICES = (
    ('sent','sent'),
    ('accepted','accepted')
) # status of relationship

class Relationship(models.Model):
    sender = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='sender') # sender: someone who want to add a friend
    receiver = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='receiver')# someone who are invited to be friend
    status = models.CharField(max_length=8,choices=STATUS_CHOICES,default='send')
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)


class Post(models.Model):
    description = models.CharField(max_length=255,blank=True)
    username = models.ForeignKey(User,on_delete=models.CASCADE)
    image = models.ImageField(upload_to = 'images',blank=True)
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.description

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    username = models.ForeignKey(User,related_name='details',on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True,blank=True)

    def __str__(self):
        return self.text

# track number of likes, who like which post
class Like(models.Model):
    username = models.ForeignKey(User,related_name='likes',on_delete=models.CASCADE)
    post = models.ForeignKey(Post,related_name='likes',on_delete=models.CASCADE)

FeedApp/forms.py
from django import forms
from .models import Post, Profile, Relationship

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['description', 'image'] 
        labels = {'description': "What would you like to say?"} #blank form labels???
    
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'email', 'dob', 'bio'] # fields displayed on the webpage
        labels = {'first_name': 'First Name', 
                    'last_name': 'Last Name', 
                    'email': 'Email', 
                    'dob': 'Date of Birth', 
                    'bio': 'Bio'} #old lable:new label displayed on the webpage

class RelationshipForm(forms.ModelForm):
    class Meta:
        model = Relationship
        fields = '__all__'
        labels = {
            'sender': 'Accept friend request from:',
            'receiver': 'Send friend request to:',
            # 'status': 
            } 
        
        

FeedApp/views.py
from django.db.models.fields import related
from django.shortcuts import render, redirect
from .forms import PostForm, ProfileForm, RelationshipForm
from .models import Post, Comment, Like, Profile, Relationship
from datetime import datetime, date


from django.contrib.auth.decorators import login_required
from django.http import Http404


# Create your views here.

# When a URL request matches the pattern we just defined, 
# Django looks for a function called index() in the views.py file.

def index(request):
    """ The home page for FeedApp. """
    return render(request, 'FeedApp/index.html')



@login_required #only after logging in, can access the profile funciton(protection)
def profile(request):
    profile = Profile.objects.filter(user=request.user) # only user that logged on can access information of their own.
    if not profile.exists():
        Profile.objects.create(user=request.user)
    profile = Profile.objects.get(user=request.user) # can use get() only when we are sure the user exists

    if request.method != 'POST':
        form = ProfileForm(instance=profile) 
    else:
        form = ProfileForm(instance=profile,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('FeedApp:index')
        
    context = {'form':form}
    return render(request,'FeedApp/profile.html',context)


@login_required
def myfeed(request):    
    comment_count_list = []
    like_count_list = []
    posts = Post.objects.filter(username=request.user).order_by('-date_posted') #username is a field of Post
    for p in posts:
        c_count = Comment.objects.filter(post=p).count()
        l_count = Like.objects.filter(post=p).count()
        comment_count_list.append(c_count)
        like_count_list.append(l_count)
    zipped_list = zip(posts, comment_count_list, like_count_list)    #pass post,comment count,like count to context or zip all up so that they are arranged in a 'dataframe' way
    
    context = {'posts':posts, 'zipped_list':zipped_list}
    return render(request, 'FeedApp/myfeed.html', context)



@login_required
def new_post(request):
    if request.method != 'POST':
        form = PostForm()
    else:
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.username = request.user
            new_post.save()
            return redirect('FeedApp:myfeed')

    context= {'form':form}
    return render(request, 'FeedApp/new_post.html', context) 


@login_required
def comments(request, post_id):
    if request.method == 'POST' and request.POST.get('btn1'):
        text = request.POST.get("comment")
        Comment.objects.create(post_id=post_id,username=request.user,text=text,date_added=date.today())

    comments = Comment.objects.filter(post=post_id)
    post = Post.objects.get(id=post_id)

    context ={'comments':comments, 'post':post}

    return render(request, 'FeedApp/comments.html', context)

@login_required
def friendsfeed(request):    
    comment_count_list = []
    like_count_list = []
    friends = Profile.objects.filter(user=request.user).values('friends')
    posts = Post.objects.filter(username__in=friends).order_by('-date_posted') #username is a field of Post
    for p in posts:
        c_count = Comment.objects.filter(post=p).count()
        l_count = Like.objects.filter(post=p).count()
        comment_count_list.append(c_count)
        like_count_list.append(l_count)
    zipped_list = zip(posts, comment_count_list, like_count_list)    #pass post,comment count,like count to context or zip all up so that they are arranged in a 'dataframe' way
    
    if request.method == 'POST' and request.POST.get('like'):
        post_to_like = request.POST.get('like')
        print(post_to_like)
        like_already_exists = Like.objects.filter(post_id=post_to_like,username=request.user)
        if not like_already_exists:
            Like.objects.create(post_id=post_to_like,username=request.user)
            return redirect('FeedApp:friendsfeed')


    context = {'posts':posts, 'zipped_list':zipped_list}
    return render(request, 'FeedApp/friendsfeed.html', context)

@login_required
def friends(request):
    # get the admin_profile and user prof to create the first relationship
    # admin_profile = Profile.objects.get(user=1)
    user_profile = Profile.objects.get(user=request.user)

    # to get My Friends
    user_friends = user_profile.friends.all()
    user_friends_profiles = Profile.objects.filter(user__in=user_friends)

    # to get Friends requsest snet
    user_relationships = Relationship.objects.filter(sender=user_profile)
    request_sent_profiles = user_relationships.values('receiver')

    # to get eligibile profiles -exlcue the user, their existing friend, and friend request sent already
    all_profiles = Profile.objects.exclude(user=request.user).exclude(id__in=user_friends_profiles).exclude(id__in=request_sent_profiles)

    # to get friend questt receive by the user
    request_received_profiles = Relationship.objects.filter(receiver=user_profile,status='sent')

    # if this is the 1st time to acesss the friend requests page, ccreate the first relationship
    # with the admin of the website(so the admin is the friends with everyone)

    # if not user_relationships.exists(): # 'filter' works with exists 'get' does not
    #     Relationship.objects.create(sender=user_profile,receiver=admin_profile,status='sent')

    # check to see WICH submit button was pressed(sending a friend reques or accep t afrind request)

    # this is to process all send request
    if request.method == 'POST' and request.POST.get('send_requests'):
        receivers = request.POST.getlist('send_requests')
        for receiver in receivers:
            receiver_profile = Profile.objects.get(id=receiver)
            Relationship.objects.create(sender=user_profile, receiver=receiver_profile,status='sent')
        return redirect('FeedApp:friends')

    # this is to process all receive request
    if request.method == 'POST' and request.POST.get('receive_requests'):
        senders = request.POST.getlist('receive_requests')
        for sender in senders:
            # updatae the realtinohsp model for the sender to status accepted
            Relationship.objects.filter(id=sender).update(status='accepted')

            # createa n realtinsoh ponject ot access the sender user id
            #  to add to the freinds list of teh suer
            relationship_obj = Relationship.objects.get(id=sender)
            user_profile.friends.add(relationship_obj.sender.user)

            # add teh user to the friends list of the sender profile
            relationship_obj.sender.friends.add(request.user)

    context = {'user_friends_profiles':user_friends_profiles, 'user_relationships':user_relationships,
    'all_profiles':all_profiles,'request_received_profiles':request_received_profiles}

    return render(request, 'FeedApp/friends.html', context)

FeedApp/templates/FeedApp/base.html
{% load bootstrap4 %}

<!doctype html>

<html lang="en">

<head>
    <meta charset="utf-8" <meta name='viewport' content='width=device-width,initial-scale=1,
        shrink-to-fit=no'>
    <title>Feed</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>

<body>
    <nav class='navbar navbar-expand-md navbar-light bg-light mb-4 border'>
        <a class='navbar-brand' href="{% url 'FeedApp:index' %}"">
            Home</a>

        <button class='navbar-toggler' type='button' data-toggle='collapse' 
            data-target='#navbarCollapse' aria-controls=" navbarCollapse" aria-expanded='false'
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id='navbarCollapse'>
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'FeedApp:profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'FeedApp:friends' %}">Friend Request</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'FeedApp:myfeed' %}">My Feed</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'FeedApp:friendsfeed' %}">Friends Feed</a>
                    </li>

                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Friend Request</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">My Feed</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Friends Feed</a>
                    </li>

                    {% endif %}
                </ul>

                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, &nbsp;{{ user.username }}.</span>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>

                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>

        <div>
            {% block content %}
            {% endblock content %}
        </div>
    </main>
</body>

</html>

FeedApp/templates/FeedApp/comments.html
{% extends 'FeedApp/base.html' %}
{% load bootstrap4 %}

{% block content %}

<h2>
    <p>Post: {{ post.description }} </p>
</h2>

<h2>
    {% if p.image %}
    <p><img src="{{post.image.url}}" class="img-thumbnail" style="max-height: 300px;" alt=""></p>
    {% endif %}
</h2>


<form method="post">
    {% csrf_token %}
    {% for c in comments %}
    <li>
        <p> {{ c.text }} &nbsp -- &nbsp {{ c.username }} </p>
    </li>

    {% empty %}
    <li> There are no comments for this post yet.</li>
    {% endfor %}

    <p><input type="text" name="comment"></p>
    <p><button type="submit" name="btn1" value=1>Submit Comment</button></p>
</form>


{% endblock content %}

FeedApp/templates/FeedApp/friends.html
{% extends 'FeedApp/base.html' %}
{% load bootstrap4 %}

{% block content %}

<style>
    table {
        font-size: 15px;
        width: auto;
    }

    th,
    td {
        border: 1px solid black;
        padding: 6px;
    }
</style>

<h2>
    <p>My Friends</p>
</h2>

<table>
    <tr>
        <th>Username</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Memeber Since</th>
    </tr>


    {% for friend in user_friends_profiles %}
    <tr>
        <td>{{ friend }}</td>
        <td>{{ friend.first_name }}</td>
        <td>{{ friend.last_name }}</td>
        <td>{{ friend.email }}</td>
        <td>{{ friend.created|date:"M d Y" }}</td>
    </tr>
    {% endfor %}
</table>
<br><br>

<h2>
    <p>Friend Request Received</p>
</h2>
<form action="{% url 'FeedApp:friends' %}" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <th>Users</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Request</th>
        </tr>

        {% for rr in request_received_profiles %}
        <tr>
            <td>{{ rr.sender }}</td>
            <td>{{ rr.sender.first_name }}</td>
            <td>{{ rr.sender.last_name }}</td>
            <td><input type="checkbox" name="receive_requests" value="{{rr.id}}" </td>
        </tr>
        {% endfor %}
    </table>
    <br><br>
    <button name="submit" class="btn btn-outline-primary" style="float: left;">Approve Request</button>
    <br><br><br><br>

    <h2>
        <p>Send a Friend Request</p>
    </h2>
    <form action="{% url 'FeedApp:friends' %}" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <th>Users</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Request</th>
            </tr>

            {% for profile in all_profiles %}
            <tr>
                <td>{{ profile }}</td>
                <td>{{ profile.first_name }}</td>
                <td>{{ profile.last_name }}</td>
                <td><input type="checkbox" name="send_requests" value="{{profile.id}}" </td>
            </tr>
            {% endfor %}
        </table>
        <br><br>
        <button name="submit" class="btn btn-outline-primary" style="float: left;">Send Request</button>
    </form>
    <br><br><br><br>

    <h2>
        <p>Friend Requests Sent</p>
    </h2>

    <table>
        <tr>
            <th>Username</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Date Sent</th>
            <th>Status</th>
        </tr>


        {% for r in user_relationships %}
        <tr>
            <td>{{ r.receiver }}</td>
            <td>{{ r.receiver.first_name }}</td>
            <td>{{ r.receiver.last_name }}</td>
            <td>{{ r.created }}</td>
            <td>{{ r.status}}</td>
        </tr>
        {% endfor %}
    </table>
    <br><br><br><br>

</form>


{% endblock content %}

FeedApp/templates/FeedApp/friendsfeed.html
{% extends 'FeedApp/base.html' %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}

{% block content %}

<h1>
    <p> Posts</p>
</h1>

<form method="post">
    {% csrf_token %}

    <table style="font-size: 25px;width: 100%;">
        {% for p,c,l in zipped_list %}

        <tr style="border: 1px solid black;padding: 6px;">
            <td>{{p.username}}:&nbsp {{ p }} <br>
                {% if p.image %}
                <img src="{{p.image.url}}" class="img-thumbnail" style="max-height: 300px;" alt="">
                {% endif %}
            </td>
        </tr>

        <tr style="border: 1px solid black;padding: 6px;">
            <td>{{p.date_posted}}</td>
            <td>
                <button type="submit" name="like" value={{ p.id }} style="background-color: transparent; border: none;">
                    Likes: &nbsp {{ l }}
                </button>
            </td>
            <td>Comments: &nbsp <a href="{% url 'FeedApp:comments' p.id %}">{{ c }} </a> &nbsp&nbsp</td>
        </tr>

        {% endfor %}
    </table>


</form>

{% endblock content %}

FeedApp/templates/FeedApp/index.html
{% extends 'FeedApp/base.html' %}


{% block page_header %}
<div class='jumbotron'>
    <h1 class='display-3'>Feed</h1>

    <p class='lead'>A Social Netowrk where you can be you.</p>

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
</div>
{% endblock page_header %}

FeedApp/templates/FeedApp/myfeed.html
{% extends 'FeedApp/base.html' %}
{% load bootstrap4 %}

{% block content %}

<h1>
    <p>My Posts</p>
</h1>
<h3><a href="{% url 'FeedApp:new_post' %}">Add a new post</a></h3>

<table style="font-size: 25px;width: 100%;">

    {% for p,c,l in zipped_list %}
    <tr style="border: 1px solid black;padding: 6px;">
        <td>{{p.username}}:&nbsp {{ p }} <br>
            {% if p.image %}
            <img src="{{p.image.url}}" class="img-thumbnail" style="max-height: 300px;" alt="">
            {% endif %}
        </td>
    </tr>

    <tr style="border: 1px solid black;padding: 6px;">
        <td>{{p.date_posted}}</td>
        <td>Likes: &nbsp {{ l }} &nbsp&nbsp&nbsp</td>
        <td>Comments: &nbsp <a href="{% url 'FeedApp:comments' p.id %}">{{ c }} </a> &nbsp&nbsp</td>
    </tr>
    {% endfor %}
</table>

{% endblock content %}

FeedApp/templates/FeedApp/new_post.html
{% extends 'FeedApp/base.html' %}
{% load bootstrap4 %}

{% block content %}
<h2>
    <p>New Post:</p>
</h2>




<form action="{% url 'FeedApp:new_post' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}

    <br><br>
    <button name='submit' class="btn btn-outline-primary">Post</button>
</form>

{% endblock content %}

FeedApp/templates/FeedApp/profile.html
{% extends 'FeedApp/base.html' %}
{% load bootstrap4 %}
<!-- can aacess all formatting inside bootstrap4, there are various classes, that can be specified e.g. to the button,  to make page looks clean and nice -->
{% load crispy_forms_tags %}
<!-- make page looks clean and nice -->

{% block content %}

<h1>
    <p>My Profile:</p>
</h1>

<form action="{% url 'FeedApp:profile' %}" method='post'>
    {% csrf_token %}
    <!--to make sure there is no malicious code -->
    {{ form |crispy}}
    <!-- load form with crispy-->
    <br><br> <!-- represnet a line break-->
    <button name="submitt" class="btn btn-outline-primary">Update</button>
    <!-- button has a blue outline and becomes dark blue when hover over it-->
</form>


{% endblock content %}